apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-redis
  labels:
    app: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deploy
  template:
    metadata:
      name: redis-deploy
      labels:
        app: redis-deploy
    spec:
      containers:
        - name: redis-deploy
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP